name: tests-orders

on:
  pull_request
    paths:
      - 'Orders/**'
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: cd Orders && npm install && npm run test:ci
  
