name: tests-payments

on:
  pull_request
    paths:
      - 'Payments/**'
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: cd Payments && npm install && npm run test:ci
  
